### ISSUE TITLE
Find EIK Sessions Not Returning Results Correctly

### ISSUE THREAD

**Issue by Ex0r** [betidestudio/EOSIntegrationKit#14]
The Find EIK Sessions node does not appear to work correctly. In testing, the first call of the node returns the correct sessions but if you run the node again (via event or whatever), it returns only a single result, which is a random available session. I have been able to replicate this 100% of the time using simple print statements and a foreach loop on the Session Results array. 

It seems to be per-client as once you close out of the client and re-open it, the first initial call works as intended then subsequent ones go back to only listing one random session at a time.

To test this, do the following steps;

Create multiple EOS sessions

Create a custom event that calls 'Find EIK Sessions' with a for each loop on the session results. On loop print a unique string for each session result. 

Call the custom event. The first time, all of the unique strings will print. 

Call the custom event again. It will only print 1 single print string, with a random unique string.

**Comment by deveshmishrabetide** [comment]
Hey! I have fixed it already in the upcoming push! Thanks a lot for reporting. (I will leave the issue open until I push it to the git and you can test once)

**Comment by justinfurnas** [comment]
Cannot wait to test it out!

**Comment by Ex0r** [comment]
Cannot wait to test it out!

**Comment by deveshmishrabetide** [comment]
Fixed on last push. Commit : 5c9d1023cf85f4e427b9a85feb7cd3c96ef1fb9b

Thank you!
