### ISSUE TITLE
Player storage 

### ISSUE THREAD

**Issue by GianniSigona** [betidestudio/EOSIntegrationKit#18]
Hi I’ve been using the eik plugin with my game for about a year now and am very thankful for an amazing plugin but unfortunately I’ve got into a problem were every 3/4 times it fails to get the saved data even though I can see it on the dashboard and 1/4 times it works.

any help will be much appreciated thanks
Gianni Sigona

**Comment by deveshmishrabetide** [comment]
Hey! You were talking of PlayerStorage right?

**Comment by deveshmishrabetide** [comment]
This has been fixed in the last commit: a36e7069508acf305217dee3c1f6b9f726d8fd9c

Let us know if you face any other issues, thank you!
