### ISSUE TITLE
Feature request: Support for multiple 'developer tool' logins

### ISSUE THREAD

**Issue by TheRealCrappyGamer** [betidestudio/EOSIntegrationKit#20]
I recently was playing around with RedPoints EOS kit and found a feature they had super useful. The ability to use the 'developer authentication tool' across multiple PIE instances. 

I am not sure internally how it does it, but when you set up your logins in the dev auth tool, you give them names of context_* (which Unreal engine maps to a separate PIE instance you have running (e.g. two PIE instances would be Context_1 and Context_2)). 

When you open the editor in PIE, if you are using the 'developer tool' login type, it automatically passes context_* (as the token) to the login method and each instance logs into their corresponding mapped dev auth tool login). 

This would be EXTREMELY useful for testing multiple multiplayer accounts locally and wouldn't require developers to create separate 'login' and 'device id' buttons for testing.

**Comment by deveshmishrabetide** [comment]
This is now fixed and added in the Version 4.
