### ISSUE TITLE
Cannot build for Linux and for Android, both from Linux

### ISSUE THREAD

**Issue by sam-cavalheiro** [betidestudio/EOSIntegrationKit#21]
Hello! I try to make build for Linux and Android from Linux, but no success.

I did to build for Linux by doing some workarounds in plugin, and worked to build Linux:
* Adding Linux as allowed platform in EOSIntegrationKit.uplugin;
* Doing this change in Source/ThirdParty/EIKSDK/EIKSDK.Build.cs (I don't remember why, but just works):
```diff
		{
			PrivateRuntimeLibraryPaths.Add(SDKBinariesDir);
			PublicAdditionalLibraries.Add(Path.Combine(SDKBinariesDir, "libEOSSDK-Linux-Shipping.so"));
-			RuntimeDependencies.Add(Path.Combine("$(TargetOutputDir)", "libEOSSDK-Linux-Shipping.so"), Path.Combine(SDKBinariesDir, "libEOSSDK-Linux-Shipping.so"));
+			/*RuntimeDependencies.Add(Path.Combine("$(TargetOutputDir)", "libEOSSDK-Linux-Shipping.so"), Path.Combine(SDKBinariesDir, "libEOSSDK-Linux-Shipping.so"));*/
			RuntimeDependencies.Add(Path.Combine(SDKBinariesDir, "libEOSSDK-Linux-Shipping.so"));
		}
		else if (Target.Platform == UnrealTargetPlatform.Mac)
```

But I don't know what do to build to Android from Linux :(
Thanks everything!

[UBT-FirstKillProject-Android-Development.txt](https://github.com/betidestudio/EOSIntegrationKit/files/14807918/UBT-FirstKillProject-Android-Development.txt)

**Comment by deveshmishrabetide** [comment]
Hey there! I haven't tried doing this myself as usually the builds I made for Android are from Windows. I will let you know soon as I will be testing this tomorrow.

**Comment by deveshmishrabetide** [comment]
Fixed in Version 4 for ever :D
