### ISSUE TITLE
Problem while initializing EIK

### ISSUE THREAD

**Issue by redtyyt** [betidestudio/EOSIntegrationKit#22]
Hello!

I'm using your plugin in UE5.1 and this happened when i started the editor after I modified some settings in Project Settings for EIK:

```
LogEOSSDK: EOS SDK binary not found: ../../../Engine/Plugins/Marketplace/EOSIntegrationKit/Binaries/Win64/EOSSDK-Win64-Shipping.dll
LogEOSSDK: Unable to find EOS SDK in project binaries: D:/Program Files/Epic Games/UE_5.1/Binaries/Win64/EOSSDK-Win64-Shipping.dll
LogEOSSDK: Loading EOS SDK from engine binaries
LogEOSSDK: Initializing EOSSDK Version:1.15.3-21924193
LogEOSSDK: LogEOS: [Boot] EOSSDK Version 1.15.3-21924193 booting at 2024-03-31T18:03:27.082Z using C
LogEOSSDK: Error: LogEOS: Incompatible EOS_Platform_Create version specified (13), expected range (1 to 12)
LogEOSSDK: Error: LogEOS: Invalid input platform options. EOS_EResult: EOS_IncompatibleVersion
LogEOSSDK: Warning: FEIKSDKManager::CreatePlatform failed. EosPlatformHandle=nullptr
LogOnline: Error: EOS: FOnlineSubsystemEOS::PlatformCreate() failed to init EOS platform
LogOnline: Warning: EOS: EOS API failed to initialize!
```

When I try to log in with `Account Portal` or `Persistent Auth` , it logs me in Device ID.

If You want other information of this issue, notify me by this e-mail:  _foxaninfos@gmail.com_ . ( _It is actually replyable :)_ )
![Screenshot 2024-03-31 201631](https://github.com/betidestudio/EOSIntegrationKit/assets/111154398/fab7c738-2b88-4065-a06f-51c52e6e2200)

If you want to know something about my game, you can find some info [here](https://foxanstudios.vercel.app/LSI.html). (translate the page because It is Italian!!)

**Comment by redtyyt** [comment]
Ok... I resolved but I can help @RoxDevvv to resolved this issue

**Comment by RoxDevvv** [comment]
Can you explain how you solved it

**Comment by redtyyt** [comment]
> Can you explain how you solved it 

Yes!
First, I sat "Default Artifact Name" and  "Artifact Name" in Project Settings to "Client" and I copied the Name of my game from the website and pasted It in Project Settings (ProductName).

At the end, I restarted the editor.

**Comment by RoxDevvv** [comment]
Worked bro thank you so muuuuuuuuuuuch 😍

**Comment by redtyyt** [comment]
> Worked bro thank you so muuuuuuuuuuuch 😍

Your welcome! I'm Happy that It worked!

**Comment by deveshmishrabetide** [comment]
Glad it got solved! Anything pending in query?
