### ISSUE TITLE
Join and Invite functionality not working

### ISSUE THREAD

**Issue by TheRealCrappyGamer** [betidestudio/EOSIntegrationKit#24]
When clicking join from overlay, or invite and accept from overlay, both server and client output the following errors:

![Screenshot_11](https://github.com/betidestudio/EOSIntegrationKit/assets/1313503/ed305b13-f6a9-42e1-a61f-310357fb9870)

https://eoshelp.epicgames.com/s/question/0D5QP000005PMST0A4/unable-to-accept-invite-through-epic-overlay-due-to-error-is-not-a-valid-product-user-id?language=en_US

There appears to be a known bug in the eos SDK but rolling back to 1.15 results in the same thing.

**Comment by deveshmishrabetide** [comment]
Fixed in push
