### ISSUE TITLE
Cant Join LAN match

### ISSUE THREAD

**Issue by CreateSGD** [betidestudio/EOSIntegrationKit#26]
I have everything setup and running just fine if I try running it online ... even though I am trying to create a LAN match EOS requires logging in so I do login, create a match, but when I try to join the match (even though both machines are online and on the same network, with the right setting for firewall) it does not work

I don't get an error I do find the session and get a success when I try to join, but nothing happens, and checking the logs tells me that it gets the right IP and port and that the second machine (Host) did get the request for connection 

Note that the same functions works just fine when I host an online match even for cross-platform  

I have tested it from the editor, and it fails, and tested it with 2 separate devices on the network and it still failed

**Comment by deveshmishrabetide** [comment]
Hey @CreateSGD, can you please drop logs for this?

**Comment by CreateSGD** [comment]
sure thing ... here is an image of the logs when I am trying to join the match ... not that 1 and success at the being are my confirmation that a session was found and the response of the join session function 

![Screenshot 2024-04-12 074612](https://github.com/betidestudio/EOSIntegrationKit/assets/131451981/34070031-f133-4bad-a04a-221a29772e84)

**Comment by deveshmishrabetide** [comment]
Hey! We have added the fixes for this on the git.

**Comment by CreateSGD** [comment]
Great ... however I am having trouble building plugins for 5.4 ATM ,,, so I will wait for the updated on the store to test it 

Thanks a lot your the best man ..
