### ISSUE TITLE
Problem while server traveling

### ISSUE THREAD

**Issue by redtyyt** [betidestudio/EOSIntegrationKit#27]
Hello! I'm RedTy (again).

I was playing my game and after the login and after creating a Lobby, I tried to server travel to my LobbyMap by this command (obviously executed by the game): `servertravel LobbyMap?listen`.

When the server travel is initializing, my game crashes and I get this:

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000028

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

Please help me resolving this issue... I really need it
![image](https://github.com/betidestudio/EOSIntegrationKit/assets/111154398/80a2c859-522f-47a4-8d96-2025fd0eb272)

**Comment by redtyyt** [comment]
> Hello! Can you share the logs?

Yes, here they are
[LSI101Alpha.log](https://github.com/betidestudio/EOSIntegrationKit/files/14910090/LSI101Alpha.log)

**Comment by deveshmishrabetide** [comment]
Sorry for late reply, but I don't see anything wrong there. Can you try running the level directly and see if it crashes?

**Comment by redtyyt** [comment]
This is what happens when I restart the game:


https://github.com/betidestudio/EOSIntegrationKit/assets/111154398/9c64f68d-43f3-468b-bb9a-59a524ae27a1

... and this is what happens when I start directly from LobbyMap:


https://github.com/betidestudio/EOSIntegrationKit/assets/111154398/541cc0aa-af18-4092-8855-f6a6257d96d8

I'm starting to think _that_ error (GetTitleData...) is the problem

**Comment by redtyyt** [comment]
I want to resolve this ASAP...

**Comment by deveshmishrabetide** [comment]
I will add a fix for this, but basically, you are trying to get the title data even before the player logs in so it doesn't have a valid user.

**Comment by deveshmishrabetide** [comment]
We have added the fix for it.

**Comment by redtyyt** [comment]
> We have added the fix for it.

What do you mean

**Comment by deveshmishrabetide** [comment]
That means it will not crash even if you are not logged in, it will just give a error out.

**Comment by redtyyt** [comment]
@deveshmishrabetide are you here?
