### ISSUE TITLE
no support on github for ue 5.4

### ISSUE THREAD

**Issue by somerandomguythatneedshelp** [betidestudio/EOSIntegrationKit#31]
When i add the plugin, it says game could not be build. try rebuilding from source manually, it worked on 5.3 but now i need to use 5.4 and this plugin doesnt support it, i understand the plugin on the marketplace supports 5.4 but this github repo doesnt

**Comment by deveshmishrabetide** [comment]
Hello! 5.4 support is present from before the release of Marketplace version, but you will have to build from source for this. Please check this video for more info : 

https://eik.betide.studio/getting-started/plugin-installation/#github-edition
https://youtu.be/FtOBmVED1i8
