### ISSUE TITLE
Start more 2 clients will freeze editor

### ISSUE THREAD

**Issue by MaltaJkee** [betidestudio/EOSIntegrationKit#48]
Hi! We have a problem with starting game as listen server with 2-3-4 players num (starting in Editor as Listen Server), when EIK is enabled. Editor goes to infinite loop and freeze. Replices on UE 5.4, EIK is 1 month ago version from main branch. 

Thread that stuck
FLegacyHttpThread::Run() HttpThread.cpp:438
FRunnableThreadWin::Run() WindowsRunnableThread.cpp:146
FRunnableThreadWin::GuardedRun() WindowsRunnableThread.cpp:71

GameThread
<unknown> 0x00007ffe5680cdf4
FEIKSDKManager::ReleaseReleasedPlatforms() EOSSDKManager.cpp:684
FEIKSDKManager::Tick(float) EOSSDKManager.cpp:557
TBaseRawMethodDelegateInstance::Execute(float) DelegateInstancesImpl.h:517
[Inlined] TDelegate::Execute(float) DelegateSignatureImpl.inl:549
FTSTicker::FElement::Fire(float) Ticker.cpp:157
FTSTicker::Tick(float) Ticker.cpp:110
FEngineLoop::Tick() LaunchEngineLoop.cpp:6161
[Inlined] EngineTick() Launch.cpp:61
GuardedMain(const wchar_t *) Launch.cpp:182
LaunchWindowsStartup(HINSTANCE__ *, HINSTANCE__ *, char *, int, const wchar_t *) LaunchWindows.cpp:247
WinMain(HINSTANCE__ *, HINSTANCE__ *, char *, int) LaunchWindows.cpp:298

**Comment by Linxmas** [comment]
You can mark it as solved.
Issue was starting PIE with overlay enabled.
