### ISSUE TITLE
Assertion failed: Pair != nullptr 

### ISSUE THREAD

**Issue by Linxmas** [betidestudio/EOSIntegrationKit#52]
No idea if you fixed it, just in case putting it here, to remind of it. :D

**Comment by Linxmas** [comment]
Seems to be more prominent in 4.2.0. As I was trying to see if lobby voice chat update bool works in all cases or no, I every time would get Assertion failed crash, had to join via ID.

**Comment by deveshmishrabetide** [comment]
Fixed in latest changesets!
