### ISSUE TITLE
Distribution of the Discord Game SDK files violates the license

### ISSUE THREAD

**Issue by hach-que** [betidestudio/EOSIntegrationKit#57]
Please be aware that you can not distribute the Discord Game SDK headers or DLL files, either on GitHub or on Fab:

- https://github.com/betidestudio/EOSIntegrationKit/blob/main/Source/DiscordGame/discord-cpp.zip
- https://github.com/betidestudio/EOSIntegrationKit/tree/main/Source/ThirdParty/DiscordGameSDK (presumably any DLL files you may distributing under this folder on Fab)

This breaks the [license agreement](https://support-dev.discord.com/hc/en-us/articles/8562894815383-Discord-Developer-Terms-of-Service) for the Discord Game SDK, which does not permit redistribution of Game SDK under Section 2B (emphasis mine):

> **_You will not_** (and will not attempt to or permit or enable others to): (a) reverse engineer or otherwise derive source code, trade secrets, or know-how from the APIs, except to the extent this restriction is prohibited by applicable laws; (b) modify, create derivative works, copy, reproduce, **_redistribute_**, rent, lease, sell, or syndicate access to **_the APIs_**; or (c) access or use the APIs in any way that (i) is not in accordance with the applicable Documentation, (ii) compromises, breaks, or circumvents any of our technical processes or security measures, (iii) poses a security vulnerability to users, us (including our systems or networks), or any third party, or (iv) exceeds any API rate, call, or other usage limits we set in our sole discretion (including as set forth in the Developer Policy or the applicable Documentation) or that we believe constitutes excessive or abusive usage.

Under Section 13 ("Definitions"):

> “APIs” (or “Developer Platform”) means, collectively, Discord’s APIs, **_software development kits (“SDKs”)_**, and other developer services and associated software (including those described in or available via our [Developer Portal](https://discord.com/developers/docs/reference)).

 This is the reason that EOS Online Subsystem does not distribute these files.

**Comment by deveshmishrabetide** [comment]
Hey June! Thanks for the heads-up. Will get this fixed asap.
